### ISSUE TITLE
Doesn't support TIFF sourcefiles

### ISSUE THREAD

**Issue by iangilman** [openzoom/node-deepzoomtools#7]
Here's my error:

```
Error: Command failed: identify: no decode delegate for this image format 
`node-deepzoomtools/originals/bees for seadragon.tiff' @ error/constitute.c/ReadImage/501.

  <<< async stack >>>
  at exports_convert__2 (node-deepzoomtools/lib/imagemagick.js:45:18)
  at DeepZoomImage_create__1 (node-deepzoomtools/lib/index.js:44:16)
  <<< raw stack >>>
    at ChildProcess._spawn.proc.on.onExit (node-deepzoomtools/node_modules/gm/lib/command.js:279:17)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by gasi** [comment]
It might be that your GraphicsMagick wasn’t compiled with TIFF support:

> GraphicsMagick requires Sam Leffler's TIFF software available via anonymous FTP at
> 
> ftp://ftp.remotesensing.org/libtiff/
> 
> or via HTTP at
> 
> http://www.remotesensing.org/libtiff/
> 
> to read the TIFF image format. It in turn optionally requires the JPEG and ZLIB libraries. Libtiff 3.8.2 or later is recommended.

– Source: http://www.graphicsmagick.org/README.html

You can confirm by running `identify -list format`.

**Comment by iangilman** [comment]
`identify -list format` Does show I don't have TIFF. Sounds like it's not a default option. I suppose we could have a little documentation for people who need it? Anyway, it's not a big deal for me; I've worked around it. Just thought I would let you know.
